--[SYSDATE : 현재 시스템의 일자와 시간] *최소 단위 1초
SELECT TO_CHAR(SYSDATE, 'RRRR-MM-DD HH24:MI:SS') "지금 시간"
  FROM DUAL;

              -- '일' 을 기준으로 - + 가능
SELECT TO_CHAR(SYSDATE-1, 'RRRR-MM-DD HH24:MI:SS') "하루 전 지금시간"
  FROM DUAL;

               -- 하루를 24시간으로 나누면 1시간
SELECT TO_CHAR(SYSDATE-1/24, 'RRRR-MM-DD HH24:MI:SS') "1시간 전 시간"
  FROM DUAL;
  
SELECT TO_CHAR(SYSDATE-1/24/60, 'RRRR-MM-DD HH24:MI:SS') "1분 전"
  FROM DUAL;
  
SELECT TO_CHAR(SYSDATE-1/24/60/60, 'RRRR-MM-DD HH24:MI:SS') "1초 전"
  FROM DUAL;
  
--[SYSTIMESTAMP : 현재 시스템의 일자와 시간] *최소 단위 10억분의 1초
SELECT TO_CHAR(SYSTIMESTAMP, 'RRRR-MM-DD HH24:MI:SS.FF3') FROM DUAL

-- 3개월 후
SELECT TO_CHAR(ADD_MONTHS(SYSDATE, 3), 'RRRR-MM-DD') FROM DUAL;
SELECT
  TO_CHAR(ADD_MONTHS(SYSDATE,6), 'RRRR-MM-DD') FROM DUAL;
  
SELECT TO_CHAR(ADD_MONTHS(SYSTIMESTAMP,4),'RRRR-MM-DD') FROM DUAL;


SELECT 
   MONTHS_BETWEEN(SYSDATE, TO_DATE('1993-07-05','RRRR-MM-DD')) 
FROM DUAL;

--현재 날짜 2022-04-17
SELECT ROUND(SYSDATE, 'MONTH') FROM DUAL;
SELECT ROUND(SYSDATE, 'YEAR') FROM DUAL;
SELECT ROUND(SYSDATE, 'DD') FROM DUAL;