--- 나의 지원목록 테이블 
  
CREATE TABLE MY_APPLY
(
   APPLY_NO       INT,
   APPLY_STATE    CHAR(5 CHAR),
   APPLY_DOC      VARCHAR2(600),
   APPLY_DATE     DATE
);

ALTER TABLE MY_APPLY
  ADD CONSTRAINT pk_my_apply_apply_no PRIMARY KEY(APPLY_NO);
  
  
--- 기업정보 테이블

CREATE TABLE COMPANY
(
   COM_NO     INT,
   COM_NAME   VARCHAR2(100),
   COM_CAT    VARCHAR2(300),
   COM_FOCUS  VARCHAR2(300),
   COM_REQ    VARCHAR2(1500),
   COM_PREF   VARCHAR2(1500),
   APPLY_NO   INT,
   COM_ETC    VARCHAR2(1500)
);

ALTER TABLE COMPANY
  ADD CONSTRAINT pk_company_com_no PRIMARY KEY(COM_NO);
  
-- FOREIGN KEY 작성
  
ALTER TABLE COMPANY
  ADD CONSTRAINT fk_company_apply_no FOREIGN KEY(APPLY_NO) REFERENCES MY_APPLY(APPLY_NO); 
  

--- 공고정보 테이블   
  
CREATE TABLE WORK_ENV
(
   ENV_IDX        INT,
   SALARY         INT,
   OVERTIME_PAY   CHAR(2 CHAR), -- Y / N
   BONUS          CHAR(2 CHAR), -- Y / N
   FACILITY       VARCHAR2(300),
   COM_NO         INT
);

ALTER TABLE WORK_ENV
  ADD CONSTRAINT pk_work_env_env_idx PRIMARY KEY(ENV_IDX);

-- FOREIGN KEY 작성
  
ALTER TABLE WORK_ENV
  ADD CONSTRAINT fk_work_env_com_no FOREIGN KEY(COM_NO) REFERENCES COMPANY(COM_NO);
  

--- 복지 수준 테이블     
  
CREATE TABLE RECRUIT_INFO
(
   REC_IDX        INT,
   COM_NO         INT,
   REC_LINK       VARCHAR2(3000),
   DOC_DATE       DATE,
   CONTEST_DATE   DATE,
   INTVW_DATE     DATE,
   REC_END        DATE
);

ALTER TABLE RECRUIT_INFO
  ADD CONSTRAINT pk_recruit_info_rec_idx PRIMARY KEY(REC_IDX);

-- FOREIGN KEY 작성
  
ALTER TABLE RECRUIT_INFO
  ADD CONSTRAINT fk_recruit_info_com_no FOREIGN KEY(COM_NO) REFERENCES COMPANY(COM_NO);
