CREATE TABLE MEMBER
(
   DEPTNO NUMBER(2),
   NAME CHAR(3 CHAR),
   GENDER CHAR(2 CHAR),
   SALARY NUMBER(5)
);

UPDATE 

INSERT INTO MEMBER VALUES(10, '김길동', '남자', 3500);
INSERT INTO MEMBER VALUES(20, '나길동', '남자', 2800);
INSERT INTO MEMBER VALUES(30, '다길동', '남자', 3000);
INSERT INTO MEMBER VALUES(10, '김영희', '여자', 3400);
INSERT INTO MEMBER VALUES(30, '나영희', '여자', 2500);
INSERT INTO MEMBER VALUES(20, '다영희', '여자', 3000);

SELECT * FROM MEMBER;

SELECT 
  DEPTNO 부서번호,
  AVG(SALARY) 급여평균,
  MAX(SALARY) 최고급여,
  MIN(SALARY) 최소급여
FROM MEMBER
GROUP BY DEPTNO
ORDER BY DEPTNO

SELECT
   DEPTNO 부서번호,
   GENDER 성별,
   COUNT(*) 인원수,
   AVG(SALARY) 급여평균
FROM MEMBER
WHERE SALARY >= 3000
GROUP BY DEPTNO, GENDER
ORDER BY DEPTNO, GENDER;

SELECT


